with_feature_location=['Anagalapura Near Hennur Main Road', 'Attibele', 'BTM Layout',
       'Begur', 'Bellandur', 'Bommasandra', 'Devanahalli',
       'Electronic City Phase 1', 'Electronic City Phase 2', 'Gottigere',
       'Harlur', 'Hebbal', 'Horamavu', 'Hosa Road', 'ITPL',
       'JP Nagar Phase 4', 'JP Nagar Phase 8',
       'Kanakapura Road Beyond Nice Ring Road',
       'Kannur on Thanisandra Main Road', 'Kasavanahalli', 'Konanakunte',
       'Koramangala', 'Krishnarajapura', 'Kudlu', 'Kumaraswamy Layout',
       'Muneshwara Nagar', 'Narayanapura on Hennur Main Road', 'RR Nagar',
       'Ramamurthy Nagar', 'Sahakar Nagar', 'Thanisandra', 'Uttarahalli',
       'Varthur', 'Whitefield Hope Farm Junction','Alaknanda', 'Burari', 'Chattarpur', 'Chittaranjan Park',
       'Dwarka Mor', 'Govindpuri', 'Jamia Nagar', 'Kalkaji',
       'Mahavir Enclave', 'Mansa Ram Park', 'Mundka', 'Paschim Vihar',
       'Pitampura', 'Saket', 'Sarita Vihar', 'Sector 11 Dwarka',
       'Sector 12 Dwarka', 'Sector 13 Dwarka', 'Sector 19 Dwarka',
       'Sector 2 Dwarka', 'Sector 22 Dwarka', 'Sector 23 Dwarka',
       'Sector 23 Rohini', 'Sector 24 Rohini', 'Sector 3 Dwarka',
       'Sector 4 Dwarka', 'Sector 5 Dwarka', 'Sector 6 Dwarka',
       'Sector 7 Dwarka', 'Sector 9 Dwarka', 'Sector-18 Dwarka',
       'Shastri Nagar', 'Uttam Nagar', 'Vasant Kunj', 'nawada','Ambattur', 'Anna Nagar', 'Avadi', 'Chromepet', 'Egmore',
       'Guduvancheri', 'Iyappanthangal', 'Iyyappanthangal', 'Karapakkam',
       'Kilkattalai', 'Kolapakkam', 'Kolathur', 'Korattur',
       'Kovilambakkam', 'Kovur', 'Madambakkam', 'Madipakkam',
       'Manapakkam', 'Manikandan Nagar', 'Medavakkam', 'Mevalurkuppam',
       'Mogappair', 'Mugalivakkam', 'Nanmangalam', 'Navallur',
       'Pallikaranai', 'Pammal', 'Perungalathur', 'Perungudi',
       'Poonamallee', 'Selaiyur', 'Sholinganallur',
       'Sunnambu Kolathur S Kolathur', 'Thiruvanmiyur', 'Thiruverkadu',
       'Thoraipakkam OMR', 'Vadapalani', 'Vengaivasal', 'tambaram west','Alwal', 'Aminpur', 'Appa Junction', 'Attapur', 'Bachupally',
       'Bachupally Road', 'Balanagar', 'Banjara Hills', 'Beeramguda',
       'Begumpet', 'Chandanagar', 'East Marredpally', 'Gachibowli',
       'Gajularamaram', 'Hitech City', 'Jubilee Hills', 'Kachiguda',
       'Kokapet', 'Kondapur', 'Krishna Reddy Pet', 'Kukatpally',
       'Madhapur', 'Malkajgiri', 'Mallampet', 'Manikonda', 'Miyapur',
       'Nallagandla Gachibowli', 'Nanakramguda', 'Narsingi', 'Nizampet',
       'Puppalaguda', 'Saket', 'Sanath Nagar', 'Serilingampally',
       'Shaikpet', 'Tellapur', 'West Marredpally','Borivali East', 'Dattapada', 'Dronagiri', 'Goregaon West',
       'Kandivali East', 'Kandivali West', 'Kharghar', 'Magathane',
       'Malad East', 'Mira Road East', 'Mira Road and Beyond',
       'Sector 17 Ulwe', 'Sector 20 Kharghar', 'Thane', 'Thane West',
       'Ulwe']

bangalore=['Anagalapura Near Hennur Main Road', 'Anekal City', 'Attibele',
       'Avalahalli Off Sarjapur Road', 'BTM Layout', 'Banashankari',
       'Banaswadi', 'Begur', 'Bellandur', 'Bommanahalli', 'Bommasandra',
       'Budigere Cross', 'Chandapura', 'Electronic City Phase 1',
       'Electronic City Phase 2', 'Gottigere', 'Harlur', 'Hebbal',
       'Hennur', 'Hennur Road', 'Horamavu', 'Hulimavu', 'ITPL',
       'JP Nagar Phase 1', 'JP Nagar Phase 4', 'JP Nagar Phase 7',
       'JP Nagar Phase 8', 'JP Nagar Phase 9', 'Jakkur', 'Junnasandra',
       'Kadugodi', 'Kalyan Nagar', 'Kammanahalli', 'Kannamangala',
       'Kannur on Thanisandra Main Road', 'Kasavanahalli', 'Kengeri',
       'Konanakunte', 'Koppa Begur Road', 'Krishnarajapura', 'Kudlu',
       'Kumaraswamy Layout', 'Kumbalgodu', 'Manyata Tech Park Nagawara',
       'Marathahalli', 'Muneshwara Nagar', 'Nagarbhavi',
       'Narayanapura on Hennur Main Road', 'Nelamangala',
       'Poornapragna Housing Society Layout', 'RR Nagar', 'Rajajinagar',
       'Ramamurthy Nagar', 'Richmond Town', 'Sahakar Nagar', 'Sarjapur',
       'Sarjapur Road Wipro To Railway Crossing', 'Subramanyapura',
       'Talaghattapura', 'Thanisandra', 'Uttarahalli', 'Varthur',
       'Whitefield Hope Farm Junction', 'Yelahanka', 'Yeshwantpur',
       'sarjapura attibele road']

chennai=['Adyar', 'Ambattur', 'Anna Nagar', 'Avadi', 'Ayanambakkam',
       'Choolaimedu', 'Chromepet', 'Egmore', 'Guduvancheri',
       'Iyappanthangal', 'Iyyappanthangal', 'Karapakkam', 'Kelambakkam',
       'Kilkattalai', 'Kolathur', 'Korattur', 'Kovilambakkam',
       'Kundrathur', 'Madambakkam', 'Madipakkam', 'Maduravoyal',
       'Manapakkam', 'Manikandan Nagar', 'Medavakkam', 'Mogappair',
       'Mugalivakkam', 'Nanmangalam', 'Navallur', 'Nungambakkam', 'Padur',
       'Pallavaram', 'Pallikaranai', 'Pammal', 'Perumbakkam',
       'Perungalathur', 'Perungudi', 'Poonamallee', 'Porur',
       'Pozhichalur', 'Raja Annamalai Puram', 'Selaiyur',
       'Sholinganallur', 'Sunnambu Kolathur S Kolathur', 'T Nagar',
       'Thiruvanmiyur', 'Thiruverkadu', 'Thoraipakkam OMR', 'Ullagaram',
       'Vadapalani', 'Vandalur', 'Velachery', 'Vengaivasal',
       'tambaram west']

delhi=['Alaknanda', 'Badarpur', 'Bindapur', 'Burari', 'Chattarpur',
       'Chittaranjan Park', 'Delhi', 'Delhi Meerut Expressway',
       'Dwarka Mor', 'Dwarka More', 'Govindpuri', 'Greater Kailash',
       'Hari Nagar', 'Jamia Nagar', 'Jasola', 'Mahavir Enclave',
       'Mansa Ram Park', 'New Ashok Nagar', 'Noida', 'Om Nagar',
       'Om Vihar', 'Paschim Vihar', 'Pitampura', 'Saket', 'Sarita Vihar',
       'Sector 11 Dwarka', 'Sector 12 Dwarka', 'Sector 13 Dwarka',
       'Sector 13 Rohini', 'Sector 19 Dwarka', 'Sector 2 Dwarka',
       'Sector 22 Dwarka', 'Sector 23 Dwarka', 'Sector 23 Rohini',
       'Sector 24 Rohini', 'Sector 5 Dwarka', 'Sector 7 Dwarka',
       'Sector 9 Dwarka', 'Sector-18 Dwarka', 'Shastri Nagar',
       'Uttam Nagar', 'Vasant Kunj', 'West Punjabi Bagh', 'nawada']

hyderabad=['Bachupally', 'Bachupally Road', 'Banjara Hills', 'Beeramguda',
       'Gachibowli', 'Gajularamaram', 'Hitech City', 'Jubilee Hills',
       'Kokapet', 'Kollur Road', 'Kondapur', 'Krishna Reddy Pet',
       'Kukatpally', 'Madhapur', 'Mallampet', 'Manikonda', 'Miyapur',
       'Nacharam', 'Nallagandla Gachibowli', 'Nanakramguda', 'Narsingi',
       'Nizampet', 'Puppalaguda', 'Saket', 'Serilingampally', 'Tellapur']

mumbai=['Airoli', 'Ambernath West', 'Andheri East', 'Andheri West',
       'Badlapur East', 'Bandra West', 'Belapur', 'Bhandup West',
       'Bhiwandi', 'Boisar', 'Borivali East', 'Borivali West', 'Chembur',
       'Dahisar', 'Dahisar West', 'Dattapada', 'Dombivali',
       'Dombivali East', 'Dronagiri', 'Ghansoli', 'Ghatkopar West',
       'Goregaon East', 'Goregaon West', 'Jogeshwari West', 'Juhu',
       'Kalwa', 'Kalyan West', 'Kamothe', 'Kandivali East',
       'Kandivali West', 'Kanjurmarg', 'Karanjade', 'Kharghar', 'Koproli',
       'Magathane', 'Malad East', 'Malad West', 'Mira Road East',
       'Mulund West', 'Naigaon East', 'Nala Sopara', 'Nalasopara West',
       'Nerul', 'Panvel', 'Parel', 'Powai', 'Sanpada', 'Sector 17 Ulwe',
       'Sector 20 Kharghar', 'Taloja', 'Thane', 'Thane West', 'Titwala',
       'Ulwe', 'Vasai', 'Ville Parle East', 'Virar', 'Virar East',
       'Wadala', 'Worli']